## Análise Exploratória de **

### Carregamento dos dados e inpeção inicial

### Conversão de tipos

### Análise consistência temporal:

### Análise de colunas categóricas

### Análise das colunas numéricas

### Análise de nulos

### Análise de duplicidades

### Análise de PK e cardinalidade

# Análise Explorotária de *olist_orders_dataset.csv*

### Carregamento dos dados e inpeção inicial

In [1]:
import pandas as pd

In [2]:
df_orders = pd.read_csv("./olist_orders_dataset.csv")

In [3]:
df_orders.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
64721,191770cd4f3a7135f4db78a9230ac3df,762e79437f60ec2d9007b5a3f97139a9,delivered,2017-12-14 18:37:44,2017-12-14 18:52:22,2017-12-21 18:54:47,2018-01-03 21:18:50,2018-01-11 00:00:00
98600,bdb80b7777496dacc3cc07faea6aa04d,a862dc8443c7881ce12cb2164fc6ca22,delivered,2018-01-28 20:46:28,2018-01-28 20:54:49,2018-01-30 02:12:58,2018-02-20 16:18:45,2018-02-23 00:00:00
1114,b760d6b613bc2bca107e3c852501e649,7cab83679b4b4b94a7783cddb27224f2,delivered,2018-01-31 20:45:16,2018-01-31 21:09:44,2018-02-16 19:28:59,2018-02-25 15:33:14,2018-03-05 00:00:00
22821,4b16d0a302a6bd19d22825d08d17d973,112a0336c86d903ae81179c5894232c2,delivered,2017-05-13 11:44:27,2017-05-13 13:02:58,2017-05-17 14:22:13,2017-05-24 18:18:46,2017-06-02 00:00:00
1976,165db2f7901b38055fe76db6894683d2,7b7ba1ea7b27f88bba9a40beb28b0520,delivered,2017-10-04 10:45:25,2017-10-04 11:05:08,2017-10-04 21:48:04,2017-10-06 17:41:40,2017-10-23 00:00:00

In [4]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

### Conversão de tipos

In [5]:
colunas_de_data = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

df_orders[colunas_de_data] = df_orders[colunas_de_data].apply(pd.to_datetime , errors = "coerce")

df_orders[colunas_de_data].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

### Análise consistência temporal:
Se valor retornado for maior que zero .: problemas estruturais nos dados nos dados

In [6]:
(df_orders["order_purchase_timestamp"] > df_orders["order_approved_at"]).sum()

np.int64(0)

In [7]:
(df_orders["order_approved_at"] > df_orders["order_delivered_carrier_date"]).sum()

np.int64(1359)

In [8]:
mask = df_orders["order_approved_at"] > df_orders["order_delivered_carrier_date"]
df_orders[mask].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04
64,688052146432ef8253587b930b01a06d,81e08b08e5ed4472008030d70327c71f,delivered,2018-04-22 08:48:13,2018-04-24 18:25:22,2018-04-23 19:19:14,2018-04-24 19:31:58,2018-05-15
199,58d4c4747ee059eeeb865b349b41f53a,1755fad7863475346bc6c3773fe055d3,delivered,2018-07-21 12:49:32,2018-07-26 23:31:53,2018-07-24 12:57:00,2018-07-25 23:58:19,2018-07-31
210,412fccb2b44a99b36714bca3fef8ad7b,c6865c523687cb3f235aa599afef1710,delivered,2018-07-22 22:30:05,2018-07-23 12:31:53,2018-07-23 12:24:00,2018-07-24 19:26:42,2018-07-31
415,56a4ac10a4a8f2ba7693523bb439eede,78438ba6ace7d2cb023dbbc81b083562,delivered,2018-07-22 13:04:47,2018-07-27 23:31:09,2018-07-24 14:03:00,2018-07-28 00:05:39,2018-08-06

In [9]:
(df_orders["order_delivered_carrier_date"] > df_orders["order_delivered_customer_date"]).sum()

np.int64(23)

In [10]:
mask = df_orders["order_delivered_carrier_date"] > df_orders["order_delivered_customer_date"]
df_orders[mask].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,5f50465da00b7fed5dd1239f4ecf6e2c,delivered,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14
9553,383aa8b2724fe452d9ccd9934a8c628b,b1cb2f9d7a19480f3749e248db14d58f,delivered,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21
13487,cb1134f9010d242e9515ad1c78ec0c39,2fd33ac77677bd214b1882868317eeed,delivered,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08
14474,dceb62e8fa94b46006c9554fed743df0,2721900eb4e0f1cc2c836dd7bc1b1e11,delivered,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11
19268,5f9d46795c3126674e52becb3a1a517f,79287bcaafdde5c793b996fc40bb7d9f,delivered,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31

### Análise de colunas categóricas

In [11]:
colunas_categoricas = [
    "order_status",
]

print(f'Porcentagem:\n{df_orders[colunas_categoricas].value_counts(normalize = True).mul(100).round(2)}\n\nValor absoluto:\n{df_orders[colunas_categoricas].value_counts()}')

Porcentagem:
order_status
delivered       97.02
shipped          1.11
canceled         0.63
unavailable      0.61
invoiced         0.32
processing       0.30
created          0.01
approved         0.00
Name: proportion, dtype: float64

Valor absoluto:
order_status
delivered       96478
shipped          1107
canceled          625
unavailable       609
invoiced          314
processing        301
created             5
approved            2
Name: count, dtype: int64

### Análise de nulos

In [12]:
print(f'{df_orders.isnull().mean().mul(100).round(2).sort_values(ascending = False)}\n\nValor absoluto:\n{df_orders.isnull().sum().sort_values(ascending = False)}')

order_delivered_customer_date    2.98
order_delivered_carrier_date     1.79
order_approved_at                0.16
order_id                         0.00
order_purchase_timestamp         0.00
order_status                     0.00
customer_id                      0.00
order_estimated_delivery_date    0.00
dtype: float64

Valor absoluto:
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
order_id                            0
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_estimated_delivery_date       0
dtype: int64

In [13]:
df_orders.groupby("order_status")[colunas_de_data].apply(lambda x: x.isnull().mean()).mul(100).round(2)

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
order_status,,,,,
approved,0.0,0.00,100.0,100.00,0.0
canceled,0.0,22.56,88.0,99.04,0.0
created,0.0,100.00,100.0,100.00,0.0
delivered,0.0,0.01,0.0,0.01,0.0
invoiced,0.0,0.00,100.0,100.00,0.0
processing,0.0,0.00,100.0,100.00,0.0
shipped,0.0,0.00,0.0,100.00,0.0
unavailable,0.0,0.00,100.0,100.00,0.0

### Análise de duplicidades

In [14]:
df_orders.duplicated().sum()

np.int64(0)

### Análise de PK e cardinalidade

In [15]:
'''
1.0         -> Possível chave
0.95 - 0.99 -> Possível chave, mas com erros 
0.5 - 0.95  -> Relacionamento (1:N)
< 0.5       -> Alta repetição .: a coluna não identifica 
'''
df_orders.nunique().sort_values().div(len(df_orders)).sort_values(ascending = False)

order_id                         1.000000
customer_id                      1.000000
order_purchase_timestamp         0.994308
order_delivered_customer_date    0.962018
order_approved_at                0.912430
order_delivered_carrier_date     0.814734
order_estimated_delivery_date    0.004616
order_status                     0.000080
dtype: float64

# Análise Exploratória de *olist_order_items_dataset.csv*

### Carregamento dos dados e inpeção inicial

In [16]:
df_order_items = pd.read_csv("./olist_order_items_dataset.csv")

In [17]:
df_order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
32971,4ab7b9945880c46a7fe643c2dacf9ce5,1,5a6e53c3b4e8684b13388d6aa4afdf12,7299e27ed73d2ad986de7f7c77d919fa,2017-04-12 19:45:14,15.99,14.52
67991,9b6c23f7e50fe64b97022b8c0d3602a6,1,2c14b8fb1b0888410324f12fc6748772,73a63f72308aa20a46f4b1632018f196,2017-06-08 15:45:13,43.95,19.59
17302,27a530fa8ac219ee1e453ccc7c575a07,1,389d119b48cf3043d311335e499d9c6b,1f50f920176fa81dab994f9023523100,2017-12-20 22:36:31,59.00,17.66
13390,1e69dcdcbc094d39d6ba64248af906fb,1,2c2a7e84b8ea741adf739c11dd78ee1a,2493dc3f20131696a0ecdb9948051a8d,2017-01-28 17:09:24,164.89,21.60
55049,7d29f6f9adf5eff8091d18cc88e4ed21,1,87351480a75abfcf15ec67af64f28ee6,ccf8813e5a7d6c84d865cd38bfc2b130,2018-05-23 03:56:18,102.00,19.68

In [18]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

### Análise das colunas numéricas

In [19]:
colunas_numericas = [
    "order_item_id",
    "price",
    "freight_value"
]

df_order_items[colunas_numericas].describe().round(2)

       order_item_id      price  freight_value
count      112650.00  112650.00      112650.00
mean            1.20     120.65          19.99
std             0.71     183.63          15.81
min             1.00       0.85           0.00
25%             1.00      39.90          13.08
50%             1.00      74.99          16.26
75%             1.00     134.90          21.15
max            21.00    6735.00         409.68

In [20]:
df_order_items[(df_order_items["order_item_id"] <= 0) | (df_order_items["price"] < 0) | (df_order_items["freight_value"] < 0)].shape[0]

0

### Conversão de tipos

In [21]:
colunas_de_data = [
    "shipping_limit_date"
]

df_order_items[colunas_de_data] = df_order_items[colunas_de_data].apply(pd.to_datetime , errors = "coerce")

df_order_items[colunas_de_data].dtypes

shipping_limit_date    datetime64[ns]
dtype: object

### Análise de nulos

In [22]:
print(f'Porcentagem:\n{df_order_items.isnull().mean().mul(100).round(2).sort_values(ascending = False)}\n\nValor absoluto:\n{df_order_items.isnull().sum().sort_values(ascending = False)}')

Porcentagem:
order_id               0.0
order_item_id          0.0
product_id             0.0
seller_id              0.0
shipping_limit_date    0.0
price                  0.0
freight_value          0.0
dtype: float64

Valor absoluto:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

### Análise de duplicidades

In [23]:
df_order_items.duplicated().sum()

np.int64(0)

### Análise de PK e cardinalidade

In [24]:
'''
1.0         -> Possível chave
0.95 - 0.99 -> Possível chave, mas com erros 
0.5 - 0.95  -> Relacionamento (1:N)
< 0.5       -> Alta repetição .: a coluna não identifica 
'''
df_order_items.nunique().div(len(df_order_items)).round(2).sort_values(ascending = False)

order_id               0.88
shipping_limit_date    0.83
product_id             0.29
freight_value          0.06
price                  0.05
seller_id              0.03
order_item_id          0.00
dtype: float64

In [25]:
df_order_items.duplicated(subset = ["order_id", "order_item_id"]).sum()

np.int64(0)

In [26]:
len(df_order_items[["order_id", "order_item_id"]].drop_duplicates()) / len(df_order_items)

1.0

# Análise Exploratória de *olist_order_payments_dataset.csv*

### Carregamento dos dados e inpeção inicial

In [27]:
df_order_payments = pd.read_csv("./olist_order_payments_dataset.csv")

In [28]:
df_order_payments.sample(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
12608,729ae5716c0955d5e326ffd5bb91368e,1,credit_card,2,44.01
46758,e87eae32b47767da815139559a6ec52e,1,credit_card,2,150.15
18336,31c2a1051b9b9899d82d9b980ec8775d,1,credit_card,1,61.85
74315,f6d0018789810848d254ef989ed2108c,1,boleto,1,50.87
35993,6963678ab394ef16d2dbed6ee6d07c44,3,voucher,1,78.89

In [29]:
df_order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

### Análise de colunas categóricas

In [30]:
colunas_categoricas = [
    "payment_type"
]

print(f'Porcentagem:\n{df_order_payments[colunas_categoricas].value_counts(normalize = True).mul(100).round(2)}\n\nValor absoluto:\n{df_order_payments[colunas_categoricas].value_counts()}')

Porcentagem:
payment_type
credit_card     73.92
boleto          19.04
voucher          5.56
debit_card       1.47
not_defined      0.00
Name: proportion, dtype: float64

Valor absoluto:
payment_type
credit_card     76795
boleto          19784
voucher          5775
debit_card       1529
not_defined         3
Name: count, dtype: int64

### Análise das colunas numéricas

In [31]:
colunas_numericas = [
    "payment_sequential",
    "payment_installments",
    "payment_value"
]

df_order_payments[colunas_numericas].describe().round(2)

       payment_sequential  payment_installments  payment_value
count           103886.00             103886.00      103886.00
mean                 1.09                  2.85         154.10
std                  0.71                  2.69         217.49
min                  1.00                  0.00           0.00
25%                  1.00                  1.00          56.79
50%                  1.00                  1.00         100.00
75%                  1.00                  4.00         171.84
max                 29.00                 24.00       13664.08

In [32]:
df_order_payments[(df_order_payments["payment_sequential"] <= 0) | (df_order_payments["payment_installments"] <= 0) | (df_order_payments["payment_value"] <= 0)]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.00
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.00
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.00
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.00
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.00
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.00

### Análise de nulos

In [33]:
print(f'Porcentagem:\n{df_order_payments.isnull().mean().mul(100).round(2)}\n\nValor absoluto:\n{df_order_payments.isnull().sum()}')

Porcentagem:
order_id                0.0
payment_sequential      0.0
payment_type            0.0
payment_installments    0.0
payment_value           0.0
dtype: float64

Valor absoluto:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

### Análise de duplicidades

In [34]:
df_order_payments.duplicated().sum()

np.int64(0)

### Análise de PK e cardinalidade

In [35]:
'''
1.0         -> Possível chave
0.95 - 0.99 -> Possível chave, mas com erros 
0.5 - 0.95  -> Relacionamento (1:N)
< 0.5       -> Alta repetição .: a coluna não identifica 
'''
df_order_payments.nunique().div(len(df_order_payments)).sort_values(ascending = False)

order_id                0.957203
payment_value           0.279893
payment_sequential      0.000279
payment_installments    0.000231
payment_type            0.000048
dtype: float64

In [36]:
'''
Caso o valor seja igual a 0 .: possível chave composta
'''
df_order_payments.duplicated(subset = ["order_id", "payment_sequential"]).sum()

np.int64(0)

In [37]:
'''
Caso o valor seja igual a 1.0 .: possível chave composta
'''
len(df_order_payments[["order_id", "payment_sequential"]].drop_duplicates()) / len(df_order_payments)

1.0

## Análise Exploratória de *olist_order_reviews_dataset.csv*

### Carregamento dos dados e inpeção inicial

In [38]:
df_order_reviews = pd.read_csv("./olist_order_reviews_dataset.csv")

In [39]:
df_order_reviews.sample(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
41274,afd8d2747c2dcc61d5c0797a021adde3,f66e426969e5222705447c43b5550df2,5,NaN,NaN,2018-03-20 00:00:00,2018-03-22 18:39:48
23591,9114c9aa04fa9703450e47a03251f510,62c0a0e72baba526d6f9c2855f8b6b97,5,NaN,"Produto muito bom e entrega rapida, obrigada",2018-04-05 00:00:00,2018-04-06 01:55:27
62710,31299ab2f257b250243533a03d8d26ff,0c8afaedb1f20b1655f3ff0d84b4424c,4,NaN,NaN,2017-07-05 00:00:00,2017-07-20 16:37:06
25041,1f1a360d7e328fbdc81dd42416edb186,d25eb73c856b09c77cd7dd09d9a488c2,5,Legal,Vai ser de muita utilidade.,2018-07-25 00:00:00,2018-07-26 18:35:40
7511,f486ddf9a94e002a3f74bef738a752a8,ca2bf936bb1f3bc31d83dd119beb1efc,1,Cor incorreta,"Recebi o produto, mas com a cor incorreta da q...",2018-07-27 00:00:00,2018-07-27 20:28:06

In [40]:
df_order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

### Conversão de tipos

In [41]:
colunas_de_data = [
    "review_creation_date",
    "review_answer_timestamp"
]

df_order_reviews[colunas_de_data] = df_order_reviews[colunas_de_data].apply(pd.to_datetime, errors = "coerce")

df_order_reviews[colunas_de_data].dtypes

review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

### Análise consistência temporal:

In [42]:
(df_order_reviews["review_creation_date"] > df_order_reviews["review_answer_timestamp"]).sum()

np.int64(0)

### Análise de colunas categóricas

In [43]:
colunas_categoricas = [
    "review_score"
]

print(f'Porcentagem:\n{df_order_reviews["review_score"].value_counts(normalize = True).mul(100).round(2).sort_values(ascending = False)}\n\nValor absoluto:\n{df_order_reviews[colunas_categoricas].value_counts().sort_values(ascending = False)}')

Porcentagem:
review_score
5    57.78
4    19.29
1    11.51
3     8.24
2     3.18
Name: proportion, dtype: float64

Valor absoluto:
review_score
5               57328
4               19142
1               11424
3                8179
2                3151
Name: count, dtype: int64

### Análise de nulos

In [44]:
print(f'Porcentagem:\n{df_order_reviews.isnull().sum().sort_values(ascending = False)}\n\nValor absoluto:\n{df_order_reviews.isnull().mean().mul(100).round(2).sort_values(ascending = False)}')

Porcentagem:
review_comment_title       87656
review_comment_message     58247
review_id                      0
review_score                   0
order_id                       0
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Valor absoluto:
review_comment_title       88.34
review_comment_message     58.70
review_id                   0.00
review_score                0.00
order_id                    0.00
review_creation_date        0.00
review_answer_timestamp     0.00
dtype: float64

In [45]:
df_order_reviews.groupby("review_score")[["review_comment_title", "review_comment_message"]].apply(lambda x: x.isnull().mean().mul(100).round(2))

              review_comment_title  review_comment_message
review_score
1                            83.60                   23.45
2                            84.83                   31.93
3                            89.93                   56.51
4                            90.94                   68.78
5                            88.39                   64.15

### Análise de duplicidades

In [46]:
df_order_reviews.duplicated().sum()

np.int64(0)

### Análise de PK e cardinalidade

In [47]:
'''
1.0         -> Possível chave
0.95 - 0.99 -> Possível chave, mas com erros 
0.5 - 0.95  -> Relacionamento (1:N)
< 0.5       -> Alta repetição .: a coluna não identifica 
'''
df_order_reviews.nunique().div(len(df_order_reviews)).sort_values(ascending = False)

order_id                   0.994447
review_id                  0.991796
review_answer_timestamp    0.990164
review_comment_message     0.364418
review_comment_title       0.045624
review_creation_date       0.006410
review_score               0.000050
dtype: float64

In [48]:
df_order_reviews.duplicated(subset = ["review_id", "order_id"]).sum()

np.int64(0)

In [49]:
len(df_order_reviews[["review_id", "order_id"]].drop_duplicates()) / len(df_order_reviews)

1.0