## Análise Explorotária de *olist_orders_dataset.csv*

### Carregamento dos dados e inpeção inicial

In [1]:
import pandas as pd

In [2]:
df_orders = pd.read_csv("./olist_orders_dataset.csv")

In [3]:
df_orders.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
66847,ee7aab7615cfc22e52462047d0e9f0db,a69a414dbd9ed9dfeb3291be9881627a,delivered,2018-05-29 08:41:45,2018-05-31 03:15:22,2018-06-07 13:08:00,2018-06-08 11:58:48,2018-06-21 00:00:00
52030,559d0bdf2fe83764fb89edea1516599a,1847c7074383b91e451c2ad8cc36ed6e,delivered,2018-06-18 22:17:37,2018-06-20 02:55:39,2018-06-20 11:14:00,2018-06-23 15:26:32,2018-06-28 00:00:00
81945,97b8321bc75e9fb96dbea17675d11ee1,4904f6af7f30637825bb794439fc1198,delivered,2018-03-09 16:50:53,2018-03-13 04:40:27,2018-03-13 22:46:53,2018-03-17 16:34:23,2018-03-27 00:00:00
6609,e6e5658805bb34a4ba873cb271def02c,d2e827a0183c03e5696c076aa6db30b9,delivered,2017-08-15 20:46:28,2017-08-17 02:50:35,2017-08-18 19:27:34,2017-09-04 20:13:07,2017-09-06 00:00:00
9272,4189fe8c734261c2d73d1d42be33b3e4,a2804a5315ad861866e3d3b39295ee40,delivered,2017-07-04 14:07:49,2017-07-05 03:04:11,2017-07-10 19:37:41,2017-07-17 20:12:34,2017-07-26 00:00:00

In [4]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

### Conversão de tipos

In [5]:
colunas_de_data = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

df_orders[colunas_de_data] = df_orders[colunas_de_data].apply(pd.to_datetime , errors = "coerce")

df_orders[colunas_de_data].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

### Análise consistência temporal:
Se valor retornado for maior que zero .: problemas estruturais nos dados nos dados

In [6]:
(df_orders["order_purchase_timestamp"] > df_orders["order_approved_at"]).sum()

np.int64(0)

In [7]:
(df_orders["order_approved_at"] > df_orders["order_delivered_carrier_date"]).sum()

np.int64(1359)

In [8]:
mask = df_orders["order_approved_at"] > df_orders["order_delivered_carrier_date"]
df_orders[mask].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04
64,688052146432ef8253587b930b01a06d,81e08b08e5ed4472008030d70327c71f,delivered,2018-04-22 08:48:13,2018-04-24 18:25:22,2018-04-23 19:19:14,2018-04-24 19:31:58,2018-05-15
199,58d4c4747ee059eeeb865b349b41f53a,1755fad7863475346bc6c3773fe055d3,delivered,2018-07-21 12:49:32,2018-07-26 23:31:53,2018-07-24 12:57:00,2018-07-25 23:58:19,2018-07-31
210,412fccb2b44a99b36714bca3fef8ad7b,c6865c523687cb3f235aa599afef1710,delivered,2018-07-22 22:30:05,2018-07-23 12:31:53,2018-07-23 12:24:00,2018-07-24 19:26:42,2018-07-31
415,56a4ac10a4a8f2ba7693523bb439eede,78438ba6ace7d2cb023dbbc81b083562,delivered,2018-07-22 13:04:47,2018-07-27 23:31:09,2018-07-24 14:03:00,2018-07-28 00:05:39,2018-08-06

In [9]:
(df_orders["order_delivered_carrier_date"] > df_orders["order_delivered_customer_date"]).sum()

np.int64(23)

In [10]:
mask = df_orders["order_delivered_carrier_date"] > df_orders["order_delivered_customer_date"]
df_orders[mask].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,5f50465da00b7fed5dd1239f4ecf6e2c,delivered,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14
9553,383aa8b2724fe452d9ccd9934a8c628b,b1cb2f9d7a19480f3749e248db14d58f,delivered,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21
13487,cb1134f9010d242e9515ad1c78ec0c39,2fd33ac77677bd214b1882868317eeed,delivered,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08
14474,dceb62e8fa94b46006c9554fed743df0,2721900eb4e0f1cc2c836dd7bc1b1e11,delivered,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11
19268,5f9d46795c3126674e52becb3a1a517f,79287bcaafdde5c793b996fc40bb7d9f,delivered,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31

### Análise de colunas categóricas

In [11]:
colunas_categoricas = [
    "order_status",
]

df_orders[colunas_categoricas].value_counts(normalize = True).mul(100).round(2)

order_status
delivered       97.02
shipped          1.11
canceled         0.63
unavailable      0.61
invoiced         0.32
processing       0.30
created          0.01
approved         0.00
Name: proportion, dtype: float64

### Análise de nulos

In [12]:
df_orders.isnull().mean().mul(100).round(2).sort_values(ascending = False)

order_delivered_customer_date    2.98
order_delivered_carrier_date     1.79
order_approved_at                0.16
order_id                         0.00
order_purchase_timestamp         0.00
order_status                     0.00
customer_id                      0.00
order_estimated_delivery_date    0.00
dtype: float64

In [13]:
df_orders.groupby("order_status")[colunas_de_data].apply(lambda x: x.isnull().mean()).mul(100).round(2)

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
order_status,,,,,
approved,0.0,0.00,100.0,100.00,0.0
canceled,0.0,22.56,88.0,99.04,0.0
created,0.0,100.00,100.0,100.00,0.0
delivered,0.0,0.01,0.0,0.01,0.0
invoiced,0.0,0.00,100.0,100.00,0.0
processing,0.0,0.00,100.0,100.00,0.0
shipped,0.0,0.00,0.0,100.00,0.0
unavailable,0.0,0.00,100.0,100.00,0.0

### Análise de duplicidades

In [14]:
df_orders.duplicated().sum()

np.int64(0)

### Análise de PK e cardinalidade

In [15]:
len(df_orders)

99441

In [16]:
df_orders.nunique().sort_values()

order_status                         8
order_estimated_delivery_date      459
order_delivered_carrier_date     81018
order_approved_at                90733
order_delivered_customer_date    95664
order_purchase_timestamp         98875
order_id                         99441
customer_id                      99441
dtype: int64

In [17]:
'''
1.0       -> Identificador (PK)
0.8 - 1.0 -> Relacionamento
< 0.8     -> Categoria
'''
(df_orders.nunique().sort_values() / len(df_orders)).sort_values(ascending = False)

order_id                         1.000000
customer_id                      1.000000
order_purchase_timestamp         0.994308
order_delivered_customer_date    0.962018
order_approved_at                0.912430
order_delivered_carrier_date     0.814734
order_estimated_delivery_date    0.004616
order_status                     0.000080
dtype: float64

# Análise Exploratória de *olist_order_items_dataset.csv*

### Carregamento dos dados e inpeção inicial

In [18]:
df_order_items = pd.read_csv("./olist_order_items_dataset.csv")

In [19]:
df_order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
58315,84c1ef4f5624b36f93862b353cd6fef0,2,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2017-11-21 04:26:55,59.90,17.67
97027,dc20ddee58064808944cd819f518dcc1,2,6abd84909e8ed79ef808c16f90b91093,da8622b14eb17ae2831f4ac5b9dab84a,2018-07-10 11:45:39,29.90,7.79
2265,052ad30f046f581349410a7b366ef674,1,c6bf8cc852eee5c4ab264e792a9c23a1,5dceca129747e92ff8ef7a997dc4f8ca,2017-06-12 12:43:10,14.00,8.72
8022,1231cdfeb0162a6f71bf9d6f9a8bf2ae,1,dd61e943598eec72351633dd6a72d5dc,cc419e0650a3c5ba77189a1882b7556a,2017-07-10 13:30:24,79.99,14.31
76650,ae86389756e9af7f5f5f64aa266a439a,1,aba86c093ccdbac75b09111d57e50004,7c67e1448b00f6e969d365cea6b010ab,2017-02-14 20:00:06,119.60,11.45

In [20]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

### Análise das colunas numéricas

In [21]:
colunas_numericas = [
    "order_item_id",
    "price",
    "freight_value"
]

df_order_items[colunas_numericas].describe().round(2)

       order_item_id      price  freight_value
count      112650.00  112650.00      112650.00
mean            1.20     120.65          19.99
std             0.71     183.63          15.81
min             1.00       0.85           0.00
25%             1.00      39.90          13.08
50%             1.00      74.99          16.26
75%             1.00     134.90          21.15
max            21.00    6735.00         409.68

In [22]:
df_order_items[(df_order_items["order_item_id"] <= 0) | (df_order_items["price"] < 0) | (df_order_items["freight_value"] < 0)].shape[0]

0

### Conversão de tipos

In [23]:
colunas_de_data = [
    "shipping_limit_date"
]

df_order_items[colunas_de_data] = df_order_items[colunas_de_data].apply(pd.to_datetime , errors = "coerce")

df_order_items[colunas_de_data].dtypes

shipping_limit_date    datetime64[ns]
dtype: object

### Análise de nulos

In [24]:
df_order_items.isnull().mean().mul(100).round(2)

order_id               0.0
order_item_id          0.0
product_id             0.0
seller_id              0.0
shipping_limit_date    0.0
price                  0.0
freight_value          0.0
dtype: float64

### Análise de duplicidades

In [25]:
df_order_items.duplicated().sum()

np.int64(0)

### Análise de PK e cardinalidade

In [26]:
len(df_order_items)

112650

In [27]:
df_order_items.nunique().sort_values()

order_item_id             21
seller_id               3095
price                   5968
freight_value           6999
product_id             32951
shipping_limit_date    93318
order_id               98666
dtype: int64

In [28]:
df_order_items.duplicated(subset = ["order_id", "order_item_id"]).sum()

np.int64(0)